### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by kumkumy2** [srosanba/sas-atom#1]
Hi, I checked your .cson file but in that couldn't find any server connection details. I do not have SAS installed on my system. I want to use Atom for writing SAS code and submit it to SAS Grid for execution. Could you please assist in this.

**Comment by srosanba** [comment]
The server connection details are buried within the batch file referenced in the "SAS Grid 9.4" command. Because the commands for submitting to a SAS Grid are going to be specific to your SAS installation, you will have to create your own batch file that plays nicely with your company's SAS Grid installation.

**Comment by kumkumy2** [comment]
Hi, could you please provide a sample of the batch file containing grid server details to connect which is referenced in the "SAS Grid 9.4" command?

**Comment by srosanba** [comment]
I have added a folder called "gridbatch" with the corresponding files (.sas, .vbs, .bat). Please note that I am not the author of these files so I will not be able to assist if anything is unclear about what is happening. Additionally, your setup will differ based on how SAS is installed on your server. Good luck.

**Comment by kumkumy2** [comment]
Hello,

Thank you for uploading the "gridbatch" folder in your repository. These (.sas, .vbs, .bat) files supports SAS9.4 version on the grid. I tried searching for .sas macro which supports SAS 9.3 version on the grid but no luck. It would be great if you could please let me know from where did you get these files so that I can check whether any such macro is available which supports SAS 9.3 on the grid.

Thanks and Regards,
Kumkum Yadav.
________________________________

**Comment by srosanba** [comment]
I have added a folder called "quickbatch" that contains the code we have for making a 9.3 connection to the same grid. Good luck.
